Move testcafe3 to public repo
GetEvinced/web-sdks-examples-pub pull request #15
Opened 2024-09-03 11:06 UTC by Dominik-Makuch-Evinced

2024-09-04 06:42 UTC, vstreltsova requested changes

2024-09-04 06:42 UTC, vstreltsova commented on testcafe/js/testcafe3/tests/home-page.js
Let's move `home-page.js` and `second-page.js` to a different folder for a better organizing, smth like:

```
tests
     |_ 
       resources
                 |_
                    home-page.js
                    second-page.js
       test-with-evinced.js
        ...
```

2024-09-04 06:42 UTC, vstreltsova commented on testcafe/js/testcafe3/before-after-hook-evSaveFile.json
Can we add all formats then if the json and html reports are pushed? May we add csv and sarif as well?
Also it's worth to put them to a separate directory called e.g. `evincedReports`

2024-09-04 06:42 UTC, vstreltsova commented on testcafe/js/testcafe3/report/testcafe3-report.html
Better to rename the directory and move there the rest of the reports

2024-09-04 06:42 UTC, vstreltsova commented on testcafe/js/testcafe3/tests/test-before-after-hooks.js
> +  await evinced.evStart();
evStart is not required here

2024-09-04 06:42 UTC, vstreltsova commented on testcafe/js/testcafe3/tests/test-before-after-hooks.js
Could you extend the example to have few tests? For example:

```
import { setCredentials, EvincedSDK } from '@evinced/js-testcafe-sdk';

let evinced;
let reportBaseName = 'evincedTest';

fixture.only `Using beforeEach and afterEach hooks for Continuous mode`
    .page `https://demo.evinced.com/`
    .before(async () => {
        await setCredentials({ // please change it according to your naming
            serviceId: process.env.AUTH_SERVICE_ID,
            secret: process.env.AUTH_SECRET,
        });
    })
    .beforeEach(async t => {
        evinced = new EvincedSDK(t);
        await evinced.evStart();
    })
    .afterEach(async t => {
        const issues = await evinced.evStop();
        console.log(`evStop: issues: ${issues.length}`)

        await evinced.evSaveFile(issues, 'html', `./${t.test.name}_${reportBaseName}.html`);
    });


test('test evStart-stop', async t => {
    await t
        .click('div:nth-child(1) > div > div.dropdown.line > p')
        .click('div:nth-child(1) > div > ul > li:nth-child(2)')
        .wait(2000); // a timeout is optional, added it to keep the test flow smooth
});

test('test evStart-stop SPA. 2 pages', async t => {
    await t.navigateTo('https://getevinced.github.io/spa-example/#/')
        .wait(1000) // this timeout is mandatory since we need some time to gather issues
        .navigateTo('https://getevinced.github.io/spa-example/#/services')
        .wait(1000) // this timeout is mandatory since we need some time to gather issues
});
```

2024-09-04 09:49 UTC, Dominik-Makuch-Evinced commented on testcafe/js/testcafe3/report/testcafe3-report.html
This is the test Cafe report, I would leave it in the current directory to not mix it with evinced report.

2024-09-05 06:57 UTC, vstreltsova approved these changes

2024-09-05 06:57 UTC, vstreltsova commented on testcafe/js/testcafe3/tests/test-with-evinced.js
> +import homePage from '../resources/home-page';
Have you pushed `resources` folder? Can't find it in the root directory 👀

2024-09-05 09:41 UTC, merged